### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by kv4nt** [phpnt/yii2-export#1]
Уважаемые, поправьте вьюху

```
if ($widget->xls) {
        echo Html::beginForm(['/export/csv'], 'post');
```

```
if ($widget->html) {
        echo Html::beginForm(['/export/pdf'], 'post');
```

**Comment by phpnt** [comment]
Здравствуйте, а тут что не так?

**Comment by kv4nt** [comment]
Ну как бы для pdf должно быть условие if ($widget->pdf) { ... для csv соответственно так же.

**Comment by phpnt** [comment]
))) Все в отпуск пора ехать, спасибо)
